import Head from 'next/head';
import Image from 'next/future/image';
import Link from 'next/link';

import joshImage from '@/images/josh.png';
import eedsDashboardImage from '@/images/eeds-dashboard.png';

const projects = [
  {
    name: 'eeds Dashboard',
    year: '2022',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'eeds Landing Page',
    year: '2022',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'COVID Stories',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'University Copyright Office',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'Oral Histories',
    year: '2020',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'Wilmeth Active Learning Center',
    year: '2019',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'eeds Mobile Application',
    year: '2018',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'Campus History',
    year: '2017',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh White</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="sm:px-12">
          <div className="mx-auto max-w-7xl bg-white">
            <div className="max-w-3xl px-16 py-12">
              <Link href="/" aria-label="Home">
                <Image
                  src={joshImage}
                  alt=""
                  sizes="4rem"
                  className="h-16 w-16 rounded-full bg-zinc-100 object-cover dark:bg-zinc-800"
                  priority
                />
              </Link>
              <h1 class="mt-12 text-4xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-5xl">
                Bringing together design and analysis to deliver delightful
                digital experiences
              </h1>
              <p class="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                I’m Josh, a full stack web developer with a special interest in
                front-end development and design. I’m currently leading efforts
                to modernize eeds. Before that, I built web applications at
                Purdue University.
              </p>
              <p class="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                I have a PhD in Analytic Philosophy from Purdue.
              </p>
            </div>

            <div className="px-16">
              <hr className="w-full border-zinc-100" />
            </div>

            <div className="py-12 px-16">
              <h2 class="text-2xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-3xl">
                Selected Projects
              </h2>

              <div className="flex flex-col divide-y">
                {projects.map((project) => (
                  <>
                    <div className="grid grid-cols-1 gap-8 py-12 md:grid-cols-[33%,1fr]">
                      <div className="flex flex-col">
                        <h3 class="text-lg font-medium tracking-tight text-zinc-800 dark:text-zinc-100 sm:text-xl sm:font-bold">
                          {project.name}
                        </h3>
                        <p className="order-first text-sm font-bold tracking-tight text-zinc-400">
                          {project.year}
                        </p>
                        <p className="mt-4 text-sm text-zinc-700">
                          {project.description}
                        </p>
                      </div>
                      <div className="">
                        <Link href="/" aria-label="Home">
                          <Image
                            src={eedsDashboardImage}
                            alt=""
                            className="h-full w-full rounded-xl bg-zinc-100 object-cover shadow-lg dark:bg-zinc-800"
                            priority
                          />
                        </Link>
                      </div>
                    </div>
                  </>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
