import Head from 'next/head';
import Image from 'next/future/image';
import Link from 'next/link';

import joshImage from '@/images/josh.png';
import eedsDashboardImage from '@/images/projects/eeds-dashboard.jpg';
import covidStoriesImage from '@/images/projects/covid-stories.jpg';
import copyrightOfficeImage from '@/images/projects/copyright-office.jpg';
import eedsAppImage from '@/images/projects/eeds-app.jpg';
import oralHistoriesImage from '@/images/projects/oral-histories.jpg';
import walcImage from '@/images/projects/walc.jpg';
import campusDatabaseImage from '@/images/projects/campus-database.jpg';

import wavesImage from '@/images/waves.svg';

import { LaravelLogo } from '@/components/logos/laravel';
import { NextLogo } from '@/components/logos/next';
import { ReactLogo } from '@/components/logos/react';
import { VueLogo } from '@/components/logos/vue';
import { TailwindLogo } from '@/components/logos/tailwind';
import { ReactNativeLogo } from '@/components/logos/react-native';

const projects = [
  {
    name: 'eeds Dashboard',
    year: '2022',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: eedsDashboardImage,
    logos: [ReactLogo, NextLogo, TailwindLogo],
  },
  // {
  //   name: 'eeds Landing Page',
  //   year: '2022',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
  //   href: '#',
  // },
  {
    name: 'University Copyright Office',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: copyrightOfficeImage,
    logos: [LaravelLogo, VueLogo, TailwindLogo],
  },
  {
    name: 'COVID Stories',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: covidStoriesImage,
    logos: [LaravelLogo, VueLogo, TailwindLogo],
  },

  {
    name: 'Oral Histories',
    year: '2020',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: oralHistoriesImage,
    logos: [LaravelLogo, VueLogo, TailwindLogo],
  },
  {
    name: 'Wilmeth Active Learning Center',
    year: '2019',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: walcImage,
    logos: [TailwindLogo],
  },
  {
    name: 'eeds Mobile Application',
    year: '2018',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: eedsAppImage,
    logos: [ReactNativeLogo],
  },
  {
    name: 'Campus History',
    year: '2017',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: campusDatabaseImage,
    logos: [LaravelLogo, VueLogo, TailwindLogo],
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh White</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="sm:px-12">
          <div className="relative mx-auto max-w-7xl bg-white">
            <div className="relative overflow-hidden">
              <div className="relative z-10 max-w-3xl px-16 py-12">
                <Link href="/" aria-label="Home">
                  <Image
                    src={joshImage}
                    alt=""
                    sizes="4rem"
                    className="h-16 w-16 rounded-full bg-zinc-100 object-cover"
                    priority
                  />
                </Link>
                <h1 className="mt-12 text-3xl font-bold tracking-tight text-zinc-800 sm:text-5xl">
                  Bringing together design and analysis to deliver delightful
                  digital experiences
                </h1>
                <p className="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                  I’m Josh, a full stack web developer with a special interest
                  in front-end development and design. I’m currently leading
                  efforts to modernize eeds. Before that, I built web
                  applications at Purdue University.
                </p>
                <p className="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                  I have a PhD in Analytic Philosophy from Purdue.
                </p>
              </div>
              <div className="absolute top-1/4 left-0 scale-150 md:top-0 md:bottom-0 md:scale-[1.15]">
                <Image
                  src={wavesImage}
                  alt=""
                  className="stroke-current"
                  priority
                />
              </div>
              <div className="absolute inset-0 bg-gradient-to-r from-white" />
              <div className="absolute inset-0 hidden bg-gradient-to-tr from-white md:block" />
            </div>

            <div className="px-16">
              <hr className="w-full border-zinc-100" />
            </div>

            <div className="z-10 py-12 px-16">
              <h2 className="text-2xl font-bold tracking-tight text-zinc-800 sm:text-3xl">
                Selected Projects
              </h2>

              <div className="flex flex-col divide-y">
                {projects.map((project, index) => (
                  <div key={index}>
                    <div className="grid grid-cols-1 gap-8 py-12 md:grid-cols-[33%,1fr]">
                      <div className="flex flex-col">
                        <h3 className="text-lg font-medium tracking-tight text-zinc-800 sm:text-xl sm:font-bold">
                          {project.name}
                        </h3>
                        <p className="order-first text-sm font-bold tracking-tight text-zinc-400">
                          {project.year}
                        </p>
                        <p className="mt-4 text-sm text-zinc-700">
                          {project.description}
                        </p>
                        {project.logos ? (
                          <div className="mt-4 flex items-center gap-x-2">
                            {project.logos.map((Logo, index) => (
                              <Logo key={index} className="h-8 w-8" />
                            ))}
                          </div>
                        ) : null}
                      </div>
                      <div className="">
                        <Link href="/" aria-label="Home">
                          <Image
                            src={project.image}
                            alt=""
                            className="h-full w-full rounded-xl bg-zinc-100 object-cover shadow-lg dark:bg-zinc-800"
                            priority
                          />
                        </Link>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
