import Head from 'next/head';
import Image from 'next/future/image';
import Link from 'next/link';

import joshImage from '@/images/josh.png';
import eedsDashboardImage from '@/images/projects/eeds-dashboard.jpg';
import covidStoriesImage from '@/images/projects/covid-stories.jpg';
import copyrightOfficeImage from '@/images/projects/copyright-office.jpg';
import eedsAppImage from '@/images/projects/eeds-app.jpg';
import oralHistoriesImage from '@/images/projects/oral-histories.jpg';
import walcImage from '@/images/projects/walc.jpg';
import campusDatabaseImage from '@/images/projects/campus-database.jpg';

import { LaravelLogo } from '@/components/logos/laravel';
import { NextLogo } from '@/components/logos/next';
import { ReactLogo } from '@/components/logos/react';
import { VueLogo } from '@/components/logos/vue';
import { TailwindLogo } from '@/components/logos/tailwind';
import { ReactNativeLogo } from '@/components/logos/react-native';

const projects = [
  {
    name: 'eeds Dashboard',
    year: '2022',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: eedsDashboardImage,
  },
  {
    name: 'eeds Landing Page',
    year: '2022',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
  },
  {
    name: 'COVID Stories',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: covidStoriesImage,
  },
  {
    name: 'University Copyright Office',
    year: '2021',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: copyrightOfficeImage,
  },
  {
    name: 'Oral Histories',
    year: '2020',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: oralHistoriesImage,
  },
  {
    name: 'Wilmeth Active Learning Center',
    year: '2019',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: walcImage,
  },
  {
    name: 'eeds Mobile Application',
    year: '2018',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: eedsAppImage,
  },
  {
    name: 'Campus History',
    year: '2017',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. A quasi culpa atque earum. Reprehenderit, porro beatae enim laudantium amet facere saepe, error numquam in voluptate rem atque, quas dolorem inventore?',
    href: '#',
    image: campusDatabaseImage,
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh White</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="sm:px-12">
          <div className="mx-auto max-w-7xl bg-white">
            <div className="max-w-3xl px-16 py-12">
              <Link href="/" aria-label="Home">
                <Image
                  src={joshImage}
                  alt=""
                  sizes="4rem"
                  className="h-16 w-16 rounded-full bg-zinc-100 object-cover dark:bg-zinc-800"
                  priority
                />
              </Link>
              <h1 className="mt-12 text-4xl font-bold tracking-tight text-zinc-800 sm:text-5xl">
                Bringing together design and analysis to deliver delightful
                digital experiences
              </h1>
              <p className="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                I’m Josh, a full stack web developer with a special interest in
                front-end development and design. I’m currently leading efforts
                to modernize eeds. Before that, I built web applications at
                Purdue University.
              </p>
              <p className="mt-6 text-base text-zinc-600 dark:text-zinc-400">
                I have a PhD in Analytic Philosophy from Purdue.
              </p>
            </div>

            <div className="px-16">
              <hr className="w-full border-zinc-100" />
            </div>

            <div className="py-12 px-16">
              <h2 className="text-2xl font-bold tracking-tight text-zinc-800 sm:text-3xl">
                Selected Projects
              </h2>

              <div className="flex flex-col divide-y">
                {projects.map((project, index) => (
                  <div key={index}>
                    <div className="grid grid-cols-1 gap-8 py-12 md:grid-cols-[33%,1fr]">
                      <div className="flex flex-col">
                        <h3 className="text-lg font-medium tracking-tight text-zinc-800 sm:text-xl sm:font-bold">
                          {project.name}
                        </h3>
                        <p className="order-first text-sm font-bold tracking-tight text-zinc-400">
                          {project.year}
                        </p>
                        <p className="mt-4 text-sm text-zinc-700">
                          {project.description}
                        </p>
                        <div className="mt-4 flex items-center gap-x-2">
                          <LaravelLogo className="h-8 w-8 text-zinc-600" />
                          <NextLogo className="h-8 w-8 text-zinc-600" />
                          <ReactLogo className="h-8 w-8 text-zinc-600" />
                          <VueLogo className="h-8 w-8 grayscale" />
                          <TailwindLogo className="h-8 w-8 grayscale" />
                          <ReactNativeLogo className="h-8 w-8 text-zinc-500 grayscale" />
                        </div>
                      </div>
                      <div className="">
                        <Link href="/" aria-label="Home">
                          <Image
                            src={project.image}
                            alt=""
                            className="h-full w-full rounded-xl bg-zinc-100 object-cover shadow-lg dark:bg-zinc-800"
                            priority
                          />
                        </Link>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
